var annotated_dup =
[
    [ "clctr_entry_t", "structclctr__entry__t.html", "structclctr__entry__t" ],
    [ "collector_args_t", "structcollector__args__t.html", "structcollector__args__t" ],
    [ "common_t", "structcommon__t.html", "structcommon__t" ],
    [ "CRC8LookupTable", "structCRC8LookupTable.html", "structCRC8LookupTable" ],
    [ "MS5611Context", "structMS5611Context.html", "structMS5611Context" ],
    [ "read_buffer", "unionread__buffer.html", "unionread__buffer" ],
    [ "Sensor", "structSensor.html", "structSensor" ],
    [ "SensorContext", "structSensorContext.html", "structSensorContext" ],
    [ "SensorLocation", "structSensorLocation.html", "structSensorLocation" ],
    [ "SensorTagData", "structSensorTagData.html", "structSensorTagData" ],
    [ "SensorTagList", "structSensorTagList.html", "structSensorTagList" ],
    [ "UBXAckPayload", "structUBXAckPayload.html", "structUBXAckPayload" ],
    [ "UBXConfigResetPayload", "structUBXConfigResetPayload.html", "structUBXConfigResetPayload" ],
    [ "UBXFrame", "structUBXFrame.html", "structUBXFrame" ],
    [ "UBXHeader", "structUBXHeader.html", "structUBXHeader" ],
    [ "UBXNavPositionPayload", "structUBXNavPositionPayload.html", "structUBXNavPositionPayload" ],
    [ "UBXNavStatusPayload", "structUBXNavStatusPayload.html", "structUBXNavStatusPayload" ],
    [ "UBXNavVelocityPayload", "structUBXNavVelocityPayload.html", "structUBXNavVelocityPayload" ],
    [ "UBXUTCPayload", "structUBXUTCPayload.html", "structUBXUTCPayload" ],
    [ "UBXValsetPayload", "structUBXValsetPayload.html", "structUBXValsetPayload" ],
    [ "vec2d_i32_t", "structvec2d__i32__t.html", "structvec2d__i32__t" ],
    [ "vec2d_t", "structvec2d__t.html", "structvec2d__t" ],
    [ "vec3d_t", "structvec3d__t.html", "structvec3d__t" ]
];